// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkipyviywkjuhvblejnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhraXB5dml5d2tqdWh2Ymxlam50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTUxNTcsImV4cCI6MjA1OTk3MTE1N30.M1APfJyjWtZY45naaMdcRRkaR4A2x7Lvn25cFu9HpSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);